baseURL = "https://boucek.me/"
languageCode = "en"
title = "boucek.me"
theme = "hugo-coder"

pagination.pagerSize = 20

pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Marian Bouček"
  info = "IT, music, horse riding"
  avatarURL = "images/avatar.jpg"
  since = 2021
  colorScheme = "auto"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/algi/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/marian-boucek-57737280/"

[[menu.main]]
  name = "Blog"
  weight = 1
  url = "blog/"
[[menu.main]]
  name = "Services"
  weight = 2
  url = "services/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
[[menu.main]]
  name = "RSS"
  weight = 4
  url = "index.xml"
  type = "application/rss+xml"
